# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[pt]
  languageCode = "pt-br"
  contentDir = "content/pt"
  title = "Leonardo G Ribeiro"
  [pt.params]
    description = "Site description in Portuguese"
#  [[pt.menu.main]]
#    name = "Wo"
#    url = "#about"
#    weight = 1
#
   [[pt.menu.main]]
     name = "Blog"
     url = "#posts"
     weight = 10

   [[pt.menu.main]]
     name = "Apresentações"
     url = "#talks"
     weight = 20


   [[pt.menu.main]]
     name = "Projetos"
     url = "#projects"
     weight = 30

   [[pt.menu.main]]
     name = "Publicações"
     url = "#publications"
     weight = 40

   [[pt.menu.main]]
     name = "Bio / Contato"
     url = "/contact"
     weight = 50

   # Link to a PDF of your resume/CV from the menu.
   # To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
   [[pt.menu.main]]
     name = "CV"
     url = "/files/LeonardoGRibeiro.html"
     weight = 60
